Added exception when listed role name is none
Caused error for command unverify list all:

AttributeError: 'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
  File "/pumpkin-py/modules/mgmt/unverify/module.py", line 635, in unverify_list
    value=", ".join(role.name for role in roles),
  File "/pumpkin-py/modules/mgmt/unverify/module.py", line 635, in <genexpr>
    value=", ".join(role.name for role in roles),
AttributeError: 'NoneType' object has no attribute 'name'